# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_auto_20160614_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(choices=[('1', 'Mon'), ('2', 'Tue'), ('3', 'Wed'), ('4', 'Thu'), ('5', 'Fri'), ('6', 'Sat'), ('7', 'Sun')])),
                ('day_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='training',
            name='day_of_week',
            field=models.IntegerField(choices=[('1', 'Mon'), ('2', 'Tue'), ('3', 'Wed'), ('4', 'Thu'), ('5', 'Fri'), ('6', 'Sat'), ('7', 'Sun')], default='1'),
        ),
    ]
